# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configs are located in `ygo-fabrica/config.toml`,
#  check that file to see possible settings.

[expansion.Custom]
default = true
recipe = ["cards/sets.toml", "cards/ojama.toml", "cards/macro.toml", "cards/hero.toml", "cards/number.toml"]


[expansion.Soul]
default = true
recipe = ["cards/sets.toml", "cards/macro.toml", "cards/soul.toml", "cards/orichalcos.toml"]

[gamedir.Custom]
path = "/run/media/monyarm/Windows 7/ProjectIgnis/"

[picset.proxy] 
mode = 'proxy'
size = '512x'
ext = 'png'
year = 2020
author = 'monyarm'
field = true 