[card.ojama-rescue]
id = 16797001
name = "Ojama Rescue"
attribute = "light"
level = 2
type = "monster effect"
race = "beast"
set = "ojama"
atk = 0
def = 1000
effect = '''
Tribute this card: Special Summon 3 Level 2 "Ojama" monsters with different names from your deck, other than "Ojama Rescue", their effects are negated untill the end of the turn.'''
ot = "CUSTOM"


[card.ojama-silver]
id = 16797002
name = "Ojama Silver"
attribute = "light"
level = 2
type = "monster pendulum effect"
race = "beast"
set = "ojama"
atk =0
def = 1000
effect = '''Once per turn, your opponent's next attack is negated.'''
pendulum-effect = '''
Once per turn: look at a number of your oponent's facedown cards, up to the number of "Ojama" Normal monsters you control (min. 1).'''
ot = "CUSTOM"


[card.ojama-lime]
id = 16797003
name = "Ojama Lime"
attribute = "light"
level = 2
type = "monster effect"
race = "beast"
set = "ojama"
atk =0
def = 1000
effect = '''
If you normal or special an "Ojama" monster, you can special summon this card from your hand.
You can only use the effect of "Ojama Lime" once per turn.'''
ot = "CUSTOM"


[card.ojama-gold]
id = 16797004
name = "Ojama Gold"
attribute = "light"
level = 2
type = "monster pendulum effect"
race = "beast"
set = "ojama"
atk =0
def = 1000
pendulum-scale = 4
effect = '''
This card can attack your opponent directly, but when it uses this effect, any battle damage it inflicts to your opponent is halved.'''
pendulum-effect = '''
Once per turn: Add an "Ojama" spell/trap card, "Treaty on Uniform Nomenclature", "League of Uniform Nomenclature", "Solidarity", "Painful Decision", "Painful Escape" or "Super Team Buddy Force Unite!" from your deck to your hand,'''
ot = "CUSTOM"


[card.ojama-black]
id = 16797005
name = "Ojama Black"
attribute = "light"
level = 2
type = "monster  effect"
race = "beast"
set = "ojama"
atk =0
def = 1000
effect = '''
When this card is Summoned while you do not control "Ojama White" in your Monster Zone: Special Summon 1 "Ojama White" from your hand or GY. You can only use this effect of "Ojama Black" once per turn.'''
ot = "CUSTOM"


[card.ojama-white]
id = 16797006
name = "Ojama White"
attribute = "light"
level = 2
type = "monster  effect"
race = "beast"
set = "ojama"
atk =0
def = 1000
effect = '''
When this card is Summoned while you do not control "Ojama Black" in your Monster Zone: Special Summon 1 "Ojama Black" from your hand or GY. You can only use this effect of "Ojama White" once per turn.'''
ot = "CUSTOM"



