[card.gem-paladin-sapphire]
name = "Gem-Paladin Draco Knight"
attribute = "light"
race = "warrior"
atk = 2500
def = 1500
level = 7
type = "monster fusion effect"
id = 144000003
set = "gem-knight crystal-beast"
effect = '''
1 "Gem-Knight monster" + 1 "Ultimate Crystal" monster or Rainbow Neos
(This card is always treated as a Gem-Knight, Crystal Beast and Ultimate Crystal monster)
This monster gains 100 ATK for each Gem-Knight monster in either player's GY and on the opponent's side of the field.
This monster gains 100 ATK for each Crystal Beast monster in either player's GY and in your Spell/Trap zones.
if this card is fusion summoned using 1 "Gem-Knight" monster your opponent controls as a fusion material, it gains its effect(s).
If this face-up card is destroyed in a Monster Zone, you can place it face-up in your Spell & Trap Zone as a Continuous Spell, instead of sending it to the GY. '''
ot = "CUSTOM"
artist = "r4children + konami + monyarm"
