# Language used is Vedic

[macro]
ORICHALCOS='''ठिस् ष्पेल्ल् चर्द् इस् इम्पेर्विओउस् तो नेगतिओन्, देस्त्रुच्तिओन्, अन्द् रेमोवल्. ईन्च्रेअसे थे आट्K पोवेर् ओf अल्ल् योउर् मोन्स्तेर्स् ब्य् ओउर् हुन्द्रेद्. योउ चोन्त्रोल् अ बच्क् रोव् ओf मोन्स्तेर्स् थत् चन्नोत् बे अत्तच्केद् व्हिले अ मोन्स्तेर् इस् इन् थे fरोन्त् रोव्. षेन्द् थिस् चर्द् fरोम् योउर् हन्द् तो थे ङ्रवेयर्द् तो नेगते अन्द् देस्त्रोय् अन्य् चर्द्. ठे सोउल् ओf व्हिछेवेर् डुएलिस्त् लोसेस् थिस् डुएल् इस् fओर्fएइत् तो थे विन्नेर्.ङ्रेअत् बेअस्त् ओf थे स्क्य्, प्लेअसे हेअर् म्य् च्र्य्.ट्रन्स्fओर्म् थ्य्सेल्f fरोम् ओर्ब् ओf लिघ्त् अन्द् ब्रिन्ग् मे विच्तोर्य् इन् थिस् fइघ्त्.एन्वेलोप् थे देसेर्त् विथ् योउर् ग्लोव् अन्द् चस्त् योउर् रगे उपोन् म्य् fओए.ऊन्लोच्क् योउर् पोवेर्स् fरोम् देएप् विथिन् सो थत् तोगेथेर् वे मय् विन्.आप्पेअर् इन् थिस् ष्हदोव् ङमे अस् ई चल्ल् योउर् नमे,विन्गेद् ड्रगोन् ओf र​! ष्लिfएर् थे स्क्य् द्रगोन्. ॐबेलिस्क् ठे टोर्मेन्तोर्.कैब​पेगस'''


[card.orichalcos-soul-gurimo]
id=121000001
name="Gurimo"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="SOUL"

[card.orichalcos-soul-pegasus]
id=121000002
name="Maximillion Pegasus"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-yugi]
id=121000003
name="Yugi Muto"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-joey]
id=121000004
name="Joey Wheeler"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-rex]
id=121000005
name="Rex Raptor"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-prisoner-1]
id=121000006
name="Prisoner"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-prisoner-2]
id=121000007
name="Prisoner"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-weevil]
id=121000008
name="Weevil Underwood"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-akiza]
id=121000009
name="Akiza Izinski"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-qrow]
id=121000010
name="Qrow Hogan"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-yusei]
id=121000011
name="Yusei Fudo"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-jack]
id=121000012
name="Jack Atlas"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-leoluna]
id=121000013
name="Leo / Luna"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-solomon]
id=121000018
name="Solomon Muto"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-seto]
id=121000019
name="Seto Kaiba"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-mokuba]
id=121000020
name="Mokuba Kaiba"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"

[card.orichalcos-soul-aleix]
id=121000021
name="Alexis Rhodes"
type="spell field"
effect = '''${ORICHALCOS}'''
ot="CUSTOM"





